[tool.poetry]
name = "zotnote"
version = "0.1.0"
description = "Streamlining reading notes with Zotero"
authors = ["bubblbu <asura.enkhbayar@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.1"
jinja2 = "^2.11.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
autopep8 = "^1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
